version: '3'
services:
  newton_raphson:
    build: ./Newton_Raphson
    ports:
      - "5000:5000"
<<<<<<< HEAD
  punto_fijo:
    build: ./punto_fijo
    ports:
      - "5003:5003"
=======

  biseccion:
    build: ./biseccion
    ports:
      - "5001:5001"
>>>>>>> Rama-Dilan
