version: '3'
services:
  newton_raphson:
    build: ./Newton_Raphson
    ports:
      - "5000:5000"
  secante:
    build: ./secante
    ports:
      - "5002:5002"
  punto_fijo:
    build: ./punto_fijo
    ports:
      - "5003:5003"
  biseccion:
    build: ./biseccion
    ports:
      - "5001:5001"
  jacobi:
    build: ./jacobi
    ports:
      - "5004:5004"
