version: '3.8'
services:
  newton_raphson:
    build: ./Newton_Raphson
    ports:
      - "5000:5000"
  secante:
    build: ./secante
    ports:
      - "5002:5002"
  punto_fijo:
    build: ./punto_fijo
    ports:
      - "5003:5003"
  biseccion:
    build: ./biseccion
    ports:
      - "5001:5001"
  gauss_seidel:
    build: ./gauss_seidel
    ports:
      - "5005:5005"
  jacobi:
    build: ./jacobi
    ports:
      - "5004:5004"
  trapecio:
    build: ./Trapecio
    ports:
      - "5006:5006"
  simpson:
    build: ./simpson
    ports:
      - "5007:5007"
  angular-app:
    build:
      context: ./proyectoF
      dockerfile: Dockerfile
    ports:
      - "5009:5009"
  euler:
    build: ./euler
    ports:
      - "5008:5008"
  ajuste_lineal_de_curvas:
    build: ./ajuste_lineal_de_curvas
    ports:
      - "5010:5010"
  